[tool.poetry]
name = "poc-oracle-aq"
version = "0.1.0"
description = ""
authors = ["Christophe <christophe.alexandre@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
oracledb = "^1.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
